# print("lstrip()去除字符串左边的空格")
# print("lstrip()结果:")
x = "   Hello World   "
print(x.lstrip())
print()
# print("rstrip()去除字符串右边的空格")
# print("rstrip()结果:")
print(x.rstrip())
print()
# print("strip()去除字符串两边的空格")
# print("strip()结果:")
print(x.strip())
print()
# print("以上方法()内的参数可以指定去除的字符，其是依次匹配是否有相同的字符，若有则去除，直到没有相同的字符为止")
# print("去除指定字符时:")
print(x.lstrip(" H"))
print(x.rstrip(" dl"))
print()
# print("removeprefix()去除指定前缀,removesuffix()去除指定后缀")
y = "Hello World"
print(y.removeprefix("Hello "))
print(y.removesuffix(" World"))
print()