# print("partition()是从左往右查找分隔符，返回一个元组，包含分隔符前的字符串、分隔符本身和分隔符后的字符串")
x = "Hello,World,Python"
print(x.partition(","))
print()
# print("rpartition()是从右往左查找分隔符，返回一个元组，包含分隔符前的字符串、分隔符本身和分隔符后的字符串")
print(x.rpartition(","))
print()
# print("split()是从左往右查找分隔符，返回一个列表，包含分隔符前的字符串和分隔符后的字符串")
# print("若separator参数为空，则会以空格为分隔符，并且会忽略字符串开头和结尾的空格")
# print("若maxsplit参数指定了分割次数(默认为-1)，则会从左往右分割指定次数，剩余的字符串会作为列表的最后一个元素")
print(x.split(" "))
print(x.split(",", 1))
print()
# print("同理rsplit()是从右往左查找分隔符")
print(x.rsplit(",", 1))
print()
# print(r"splitlines()是以换行符为分隔符进行分割(按行分割,\r\n均可以)，返回一个列表")
# print("其中的keepends参数表示是否保留换行符，默认为False")
y = "Hello\nWorld\nPython"
print(y.splitlines())
print(y.splitlines(True))