year = 2007
print("I was born in {}".format(year))
print(f"I was born in {year}")
print()
# print("∵format()参数中的字符串会被当成元组的元素来对待,如:")
x = "{} was born in {}".format("I", year)
print(x)
# print("∴{}中的数字参数为format()方法的参数索引,如:")
y = "{1} was born in {0}".format("I", year)
print(y)
z = "{0}{0}{1}{1}".format("Yes","No")
print(z)
print()
# print("使用关键字参数,如:")
a = "{name} was born in {year}".format(name="I", year=year)
print(a)
print()
# print("若想输出{}本身:")
print("{}, {}, {}".format("{}", "{}", "{}"))
print("{{}}, {{}}, {{}}".format())
print()
# print("{:[align]},这个参数表示对齐方式,可以是<、>、^分别表示左对齐、右对齐和居中对齐,默认是右对齐
# print("{:[align][width]},width表示输出的宽度,若输出的字符串长度小于这个宽度,则会在内容的左边或右边补多出来数量的空格,若小于等于原字符串长度,则输出原字符串")
# print("对于'^'(居中符),同样是先右后左地填充,对于原字符串来讲,就是先左后右地对齐)
# print("=则表示在符号后面但数字前强制填充空格")
print("{:^7}".format("Hello"))
# print("[align]和[width]之间或之前可以加上一个0(即:后,[width]前均可),表示用那个0代替空格去填充,\n而它们之前还可以加上任一符号或者0,表示用这个符号或0代替空格去填充")
print("{1:>10}{0:<10}".format("Hello", "World"))
print("{left:>010}{right:<010}".format(left="-Hello", right="World"))
print("{left:%>10}{right:%<10}".format(left="Hello", right="World"))
# print("对于数字(如上,字符串不行),可以在[width]前加符号,填充0时会在符号后面填充0,如:")
print("{:010}".format(-520))
# print("来自DeepSeek:\n{:[填充字符][对齐][符号][#][0][宽度][,][.精度][类型]}")