# print("将可迭代对象转化为列表，list()")
x, y = list("12345"), list((1, 2, 3, 4, 5))
print(x, y)
print(type(x))
print()
# print("将可迭代对象转化为元组，tuple()")
a, b = tuple("321"), tuple([3, 2, 1])
print(type(a))
print(a, b)
print()
# print("将可迭代对象转化为字符串，str()")
i = str([6, 7, 8, 9])
print(i)
print(type(i))